#!/bin/bash

set -e

APP_NAME=fiona

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    upgrade)
	echo "upgrade called"
    ;;

    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
		if [ "$1" = "remove" ]; then
		  # Remove all
		  rm -rf /opt/$APP_NAME || true
		fi

		# --------------------------------------
		# remove service
		# --------------------------------------
		if [ -x "/etc/init.d/$APP_NAME" ] || [ -e "/etc/init/$APP_NAME.conf" ]; then
		        if [ ! -e "/etc/init/$APP_NAME.conf" ]; then
		                update-rc.d $APP_NAME disable >/dev/null
		        fi
		fi

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
