#!/bin/bash

set -e

APP_NAME=fiona

case "$1" in

  remove)
    #####################################################################
    #Stop the service 
	echo "Going to stop service..."
	service $APP_NAME stop || true
	echo "Service $APP_NAME stopped."
    #####################################################################
  ;;

  upgrade|deconfigure|failed-upgrade)
    exit 0
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0

