import { BrowserTreeObject } from '../types/Browser';
import { BookmarkData, HistoryData } from 'common-interfaces/types/Browser';
import * as API from '../api/types'

const BROWSERS: BrowserTreeObject[] = [{
  id: 0,
  parentId: null,
  name: 'Chrome',
  type: 'browser',
  icon: 'chrome',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 1,
  parentId: null,
  name: 'Firefox',
  type: 'browser',
  icon: 'firefox',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 2,
  parentId: null,
  name: 'Explorer',
  type: 'browser',
  icon: 'explorer',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 3,
  parentId: null,
  name: 'Opera',
  type: 'browser',
  icon: 'opera',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 4,
  parentId: 0,
  name: 'Bookmarks Bar',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: true,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 5,
  parentId: 4,
  name: 'Favourites',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: true,
  hasNotes: true,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 6,
  parentId: 0,
  name: 'Chuck Norris jokes',
  type: 'site',
  icon: 'fitness_center',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: true,
  isRead: false,
  tags: [],
}, {
  id: 7,
  parentId: 5,
  name: 'What is my ip address',
  type: 'site',
  icon: 'fitness_center',
  url: 'http://www.whatismyipaddress.com',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 8,
  parentId: 0,
  name: 'Travel',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 9,
  parentId: 8,
  name: 'airbnb',
  type: 'site',
  icon: 'bookmark',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 10,
  parentId: 8,
  name: 'Tripadvisor',
  type: 'site',
  icon: 'bookmark',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 11,
  parentId: 8,
  name: 'Expedia',
  type: 'site',
  icon: 'bookmark',
  url: '',
  isFavorite: false,
  hasNotes: true,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 12,
  parentId: 0,
  name: 'Business',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 13,
  parentId: 1,
  name: 'All Mail',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 14,
  parentId: 13,
  name: 'Gmail',
  type: 'site',
  icon: 'mail',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 15,
  parentId: 13,
  name: 'Yahoo',
  type: 'site',
  icon: 'mail',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 16,
  parentId: 13,
  name: 'Hotmail',
  type: 'site',
  icon: 'mail',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 17,
  parentId: 13,
  name: 'MailBox',
  type: 'site',
  icon: 'mail',
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 18,
  parentId: 1,
  name: 'Team',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: true,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 19,
  parentId: 1,
  name: 'Terror',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: [],
}, {
  id: 20,
  parentId: 13,
  name: 'Test Folder',
  type: 'directory',
  icon: null,
  url: '',
  isFavorite: false,
  hasNotes: false,
  hasTranslation: false,
  isRead: true,
  tags: []
}];

const HISTORY =  [{
  id: 0,
  time: 1418302440,
  title: {
    name: 'Iron - Google Search',
    icon: 'photo',
  },
  url: 'https://www.google.com',
  extraUrl: '/search?q=browser&biw=1920&bih=...',
  browser: {
    name: 'Chrome',
    icon: 'chrome',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 1,
  marker: 1,
  time: 1418302380,
  title: {
    name: 'Bomb - Google Search',
    icon: 'photo',
  },
  url: 'https://www.google.com',
  extraUrl: '/search?q=browser&biw=1920&bih=...',
  browser: {
    name: 'Chrome',
    icon: 'chrome',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 2,
  time: 1418302260,
  title: {
    name: 'Login - Dropbox',
    icon: 'fingerprint',
  },
  url: 'https://www.dropbox.com',
  extraUrl: '/login?cont=https%3A%2F%2Fwww...',
  browser: {
    name: 'Chrome',
    icon: 'chrome',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 3,
  time: 1418296080,
  title: {
    name: 'Mapping, Traffic & Navigation App',
    icon: 'flight_land',
  },
  url: 'https://www.waze.com',
  extraUrl: '',
  browser: {
    name: 'Chrome',
    icon: 'chrome',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 4,
  marker: 0,
  time: 1418292840,
  title: {
    name: 'Inbox - BebJ@gmail.com - Gmail',
    icon: 'email',
  },
  url: 'https://mail.google.com',
  extraUrl: '/mail/u/0#search/%D7%90%D7%...',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: true,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 5,
  marker: 0,
  time: 1418292120,
  title: {
    name: 'Fire - Google Search',
    icon: 'photo',
  },
  url: 'https://www.google.com',
  extraUrl: '/search?q=browser&biw=1920&bih=...',
  browser: {
    name: 'Chrome',
    icon: 'chrome',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: false,
  tags: []
}, {
  id: 6,
  time: 1418255520,
  title: {
    name: 'Pasta Recipes | SimplyRecipes.com',
    icon: 'local_bar',
  },
  url: 'https://www.simplyrecipes.com',
  extraUrl: '/recipes/ingredient/pasta',
  browser: {
    name: 'Explorer',
    icon: 'explorer',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 7,
  time: 1418255460,
  title: {
    name: 'Chicken Recipes | SimplyRecipes.com',
    icon: 'restaurant',
  },
  url: 'https://www.simplyrecipes.com',
  extraUrl: '/recipes/ingredient/chicken',
  browser: {
    name: 'Explorer',
    icon: 'explorer',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: true,
  isRead: true,
  tags: []
}, {
  id: 8,
  time: 1418255400,
  title: {
    name: 'Simply Recipes Food and Cooking Blog',
    icon: 'restaurant',
  },
  url: 'https://www.simplyrecipes.com',
  extraUrl: '',
  browser: {
    name: 'Explorer',
    icon: 'explorer',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 9,
  time: 1418254860,
  title: {
    name: 'Car Rental: Find Rental Car Deals | Expedia',
    icon: 'local_taxi',
  },
  url: 'https://www.expedia.com',
  extraUrl: '/cars',
  browser: {
    name: 'Opera',
    icon: 'opera',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 10,
  time: 1418254560,
  title: {
    name: 'Expedia Travel: Vacations, Flights, Airline Tickets',
    icon: 'local_taxi',
  },
  url: 'https://www.expedia.com',
  extraUrl: '',
  browser: {
    name: 'Opera',
    icon: 'opera',
    url: '',
  },
  isFavorite: true,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 11,
  time: 1418253660,
  title: {
    name: 'Iron - Google Search',
    icon: 'photo',
  },
  url: 'https://www.google.com',
  extraUrl: '',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: false,
  hasTranslation: true,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 12,
  time: 1418253600,
  title: {
    name: 'Google',
    icon: 'photo',
  },
  url: 'https://www.google.com',
  extraUrl: '/search?q=browser&biw=1920&bih=...',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 13,
  time: 1418251920,
  title: {
    name: 'Vacation Rentals, Homes, Places - Airbnb',
    icon: 'flight',
  },
  url: 'https://www.airbnb.com',
  extraUrl: '/rooms/817858',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 14,
  time: 1418251800,
  title: {
    name: 'Vacation Rentals, Homes, Places - Airbnb',
    icon: 'flight',
  },
  url: 'https://www.airbnb.com',
  extraUrl: '',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}, {
  id: 15,
  time: 1418246940,
  title: {
    name: 'Inbox - BebJ@gmail.com - Gmail',
    icon: 'email',
  },
  url: 'https://mail.google.com',
  extraUrl: '/mail/u/0#search/%D7%90%D7%...',
  browser: {
    name: 'Firefox',
    icon: 'firefox',
    url: '',
  },
  isFavorite: false,
  hasTranslation: false,
  hasNotes: false,
  isRead: true,
  tags: []
}];

export const demoBrowserData = {
  browserData: {
    bookmarks: {
      extracted: 1490861885,
      browsers: (BROWSERS),
    },
    history: HISTORY,
    timerIndicator: 1490861885000,
    updateTimeIndicator: 200000,
  }
};

export const serverBookmarks: BookmarkData[] = [{
  id: '59888880cc87e8074602c65b',
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: '2017-06-08 13:50:12.934',
  name: 'Anonymous',
  icon: 'chrome',
  type: 'site',
  browser: 'chrome',
  parentId: null,
  hitRate: '0',
  url: 'https://www.google.nl/search?q=jingly&oq=jingly&aqs=chrome..69i57j0l3.1663j0j4&client=m' +
  's-android-samsung&sourceid=chrome-mobile&ie=UTF-8'
}, {
  id: '59888880cc87e8074602c65a',
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: '2017-06-06 11:20:20.715',
  name: 'Anonymous',
  icon: 'chrome',
  type: 'site',
  browser: 'chrome',
  parentId: null,
  hitRate: '0',
  url: 'https://giphy.com/search/good-night'
}];

// tslint:disable
export const serverHistory: HistoryData[] = [{
  id: "59888880cc87e8074602c6a0",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:41.522",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "3",
  url: "http://m.ndtv.com/"
}, {
  id: "59888880cc87e8074602c6a7",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:41.522",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "3",
  url: "http://m.ndtv.com/"
}, {
  id: "59888880cc87e8074602c6e1",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:41.522",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "http://m.ndtv.com/"
}, {
  id: "59888880cc87e8074602c6a8",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "http://doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6a1",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "http://doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6e3",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6a2",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6a3",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323"
}, {
  id: "59888880cc87e8074602c6e4",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323"
}, {
  id: "59888880cc87e8074602c6aa",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323"
}, {
  id: "59888880cc87e8074602c6e2",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "http://doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6a9",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:39.604",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "http://m.doctor.ndtv.com/news/drinking-alcohol-might-improve-your-memory-1729323?pfrom=home-wapextra3"
}, {
  id: "59888880cc87e8074602c6ab",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:32.594",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "http://m.ndtv.com/india-news/pm-modi-tweets-praise-for-nitish-kumar-10-point-guide-to-bihar-crisis-1729576?pfrom=home-topstories"
}, {
  id: "59888880cc87e8074602c6e5",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:32.594",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "http://m.ndtv.com/india-news/pm-modi-tweets-praise-for-nitish-kumar-10-point-guide-to-bihar-crisis-1729576?pfrom=home-topstories"
}, {
  id: "59888880cc87e8074602c6a4",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:32.594",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "http://m.ndtv.com/india-news/pm-modi-tweets-praise-for-nitish-kumar-10-point-guide-to-bihar-crisis-1729576?pfrom=home-topstories"
}, {
  id: "59888880cc87e8074602c6ac",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:27.829",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=C4hjWbeiHdGy0gXa4Z_ADQ&q=ndtv&oq=ndtv&gs_l=mobile-gws-serp.3..0i131k1j0l2j0i67k1j0.2799.3519.0.3793.5.5.0.1.1.0.191.684.1j4.5.0....0...1.1j4.64.mobile-gws-serp..0.5.555.3..41.NquT0soOVsI"
}, {
  id: "59888880cc87e8074602c6a5",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:27.829",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=C4hjWbeiHdGy0gXa4Z_ADQ&q=ndtv&oq=ndtv&gs_l=mobile-gws-serp.3..0i131k1j0l2j0i67k1j0.2799.3519.0.3793.5.5.0.1.1.0.191.684.1j4.5.0....0...1.1j4.64.mobile-gws-serp..0.5.555.3..41.NquT0soOVsI"
}, {
  id: "59888880cc87e8074602c6e6",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:27.829",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=C4hjWbeiHdGy0gXa4Z_ADQ&q=ndtv&oq=ndtv&gs_l=mobile-gws-serp.3..0i131k1j0l2j0i67k1j0.2799.3519.0.3793.5.5.0.1.1.0.191.684.1j4.5.0....0...1.1j4.64.mobile-gws-serp..0.5.555.3..41.NquT0soOVsI"
}, {
  id: "59888880cc87e8074602c6e7",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:22.083",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c6ad",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:22.083",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c6a6",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-26 17:49:22.083",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c673",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:35.022",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c65c",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:35.022",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c4b6",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:35.022",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?client=ms-android-samsung&ei=_YdjWc21OpLEwQL1rYDwCw&q=profile+picture&oq=profile+picture&gs_l=mobile-gws-serp.12..0i71k1l5.0.0.0.11252.0.0.0.0.0.0.0.0..0.0....0...1..64.mobile-gws-serp..0.0.0.1jnD4MNxL4M"
}, {
  id: "59888880cc87e8074602c674",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:21.464",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?q=profile+picture&oq=profile+picture&aqs=chrome..69i57j0l3.3118j0j4&client=ms-android-samsung&sourceid=chrome-mobile&ie=UTF-8"
}, {
  id: "59888880cc87e8074602c6e8",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:21.464",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://www.google.nl/search?q=profile+picture&oq=profile+picture&aqs=chrome..69i57j0l3.3118j0j4&client=ms-android-samsung&sourceid=chrome-mobile&ie=UTF-8"
}, {
  id: "59888880cc87e8074602c65d",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:21.464",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://www.google.nl/search?q=profile+picture&oq=profile+picture&aqs=chrome..69i57j0l3.3118j0j4&client=ms-android-samsung&sourceid=chrome-mobile&ie=UTF-8"
}, {
  id: "59888880cc87e8074602c4b7",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:21.464",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "1",
  url: "https://www.google.nl/search?q=profile+picture&oq=profile+picture&aqs=chrome..69i57j0l3.3118j0j4&client=ms-android-samsung&sourceid=chrome-mobile&ie=UTF-8"
}, {
  id: "59888880cc87e8074602c6e9",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:14.989",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://m.facebook.com/help/245058342280723?refsrc=https%3A%2F%2Fm.facebook.com%2Fhelp%2F121104481304395&_rdr"
}, {
  id: "59888880cc87e8074602c675",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:14.989",
  name: "Anonymous",
  icon: "device",
  type: "site",
  browser: "device",
  parentId: null,
  hitRate: "2",
  url: "https://m.facebook.com/help/245058342280723?refsrc=https%3A%2F%2Fm.facebook.com%2Fhelp%2F121104481304395&_rdr"
}, {
  id: "59888880cc87e8074602c4b8",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:14.989",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: "2",
  url: "https://m.facebook.com/help/245058342280723?refsrc=https%3A%2F%2Fm.facebook.com%2Fhelp%2F121104481304395&_rdr"
}, {
  id: "59888880cc87e8074602c65e",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-10 15:58:14.989",
  name: "Anonymous",
  icon: "chrome",
  type: "site",
  browser: "chrome",
  parentId: null,
  hitRate: '0',
  url: "https://m.facebook.com/help/245058342280723?refsrc=https%3A%2F%2Fm.facebook.com%2Fhelp%2F121104481304395&_rdr"
}, {
  id: "59888880cc87e8074602c4ca",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-05 16:32:15.396",
  name: "Anonymous",
  icon: "samsung",
  type: "site",
  browser: "samsung",
  parentId: null,
  hitRate: "3",
  url: "http://www.samsung.com/nl/welcome/?ref=inforain"
}, {
  id: "59888880cc87e8074602c4cb",
  tags: [],
  isFavorite: false,
  isRead: false,
  timestamp: "2017-07-05 16:31:56.317",
  name: "Anonymous",
  icon: "samsung",
  type: "site",
  browser: "samsung",
  parentId: null,
  hitRate: "1",
  url: "http://www.weeronline.nl/"
}];

// tslint:enable

const demoServerHistoryData = [];

let counter = serverHistory.length;
for (let i = 1; i < 500; i++) {
  counter --;
  if (counter < 0) {
    counter = serverHistory.length - 1;
  }
  demoServerHistoryData.push(serverHistory[counter]);
}

export const getServerHistoryMockData = (query: API.ApiQueryParams) => {
  return demoServerHistoryData.slice(query.skip, query.skip + query.limit);
}
