export interface ThemeProps {
  viewerBackground: string,
  urlPanelTitleColor: string,
  urlPanelBackground: string,
  urlPanelContentBorder: string,
  linkColor: string,
  textColor: string,
  highlightColor: string,
  slidePanelTitleColor: string,
  slidePanelBackground: string,
  slidePanelContentBorder: string,
  keyLoggerTitleColor: string,
  keyLoggerPanelContentBorder: string,
  keyLoggerContextColor: string,
  filmStripBg: string,
  controlsPanelBackground: string,
  controlsPanelTextColor: string,
  controlsPanelDisabledTextColor: string,
}

export const defaultTheme = {
  viewerBackground: 'white',
  urlPanelTitleColor: 'black',
  urlPanelBackground: 'cyan',
  urlPanelContentBorder: '1px solid blue',
  linkColor: 'purple',
  textColor: 'black',
  highlightColor: 'gray',
  slidePanelTitleColor: 'black',
  slidePanelBackground: 'silver',
  slidePanelContentBorder: '1px solid gray',
  keyLoggerTitleColor: 'white',
  keyLoggerPanelBackground: 'orange',
  keyLoggerPanelContentBorder: '1px solid red',
  keyLoggerContextColor: 'white',
  filmStripBg: 'DeepSkyBlue ',
  controlsPanelBackground: 'WhiteSmoke',
  controlsPanelTextColor: 'SlateGray',
  controlsPanelDisabledTextColor: 'silver',
}
