export const APP_SYMBOLS = {
  all: {key: 'phone', caption: 'Phone', },
  line: {key: 'line', caption: 'Line', icon: 'line'},
  hangouts: {key: 'hangouts', caption: 'Hangouts', icon: 'hangouts'},
  phone: {key: 'phone', caption: 'Phone'},
  whatsapp: {key: 'whatsapp', caption: 'Whatsapp'},
  skype: {key: 'skype', caption: 'Skype'},
  mail: {key: 'mail', caption: 'Mail'},
  facebook_messenger: {key: 'facebook_messenger', caption: 'Facebook'},
  facebook: {key: 'facebook', caption: 'Facebook', icon: 'facebook'},
  home: {key: 'phoneHome', caption: 'Home'},
  telegram: {key: 'telegram', caption: 'Telegram'},
  viber: {key: 'viber', caption: 'Viber'},
  sms: {key: 'sms', caption: 'SMS'},
  created: {key: 'created', caption: 'created', icon: 'doc_new'},
  modified: {key: 'modified', caption: 'modified', icon: 'doc_edit'},
  accessed: {key: 'accessed', caption: 'star rate', icon: 'doc_new'},
  deleted: {key: 'deleted', caption: 'deleted', icon: 'doc_delete'},
  notebook: {key: 'notebook', caption: 'notebook', icon: 'notebook'},
  google: {key: 'google', caption: 'Google'},
  yahoo: {key: 'yahoo', caption: 'Yahoo'},
  amazon: {key: 'amazon', caption: 'Amazon'},
  dropbox: {key: 'dropbox', caption: 'Dropbox'},
  twitter: {key: 'twitter', caption: 'Twitter'},
  linkedin: {key: 'linkedin', caption: 'Linkedin'},
  chrome: {key: 'chrome', caption: 'Chrome'},
  googledrive: {key: 'gdrive', caption: 'Google Drive'},
  firefox: {key: 'firefox', caption: 'Firefox'},
  ie: {key: 'ie', caption: 'IE'},
  safari: {key: 'safari', caption: 'Safari'},
  word: {key: 'word', caption: 'Word', icon: 'doc_word'},
  sound: {key: 'sound', caption: 'Sound', icon: 'doc_sound'},
  pdf: {key: 'pdf', caption: 'PDF', icon: 'doc_pdf'},
  pic: {key: 'pic', caption: 'Picture', icon: 'doc_pic'},
  excel: {key: 'excel', caption: 'Excel', icon: 'doc_excel'},
  txt: {key: 'txt', caption: 'Text', icon: 'notebook'},
  outgoing: {key: 'outgoing', caption: 'Outgoing', icon: 'call_outgoing'},
  incomming: {key: 'incomming', caption: 'Incomming', icon: 'call_incomming'},
  unanswered: {key: 'unanswered', caption: 'Unanswered', icon: 'call_unanswered'},
};

export interface AppSymbol {
  key: string,
  caption: string,
  icon?: string
}
